spring.datasource.url=jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/${DB_DATABASE}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=update
spring.profiles.active=dev

logging.level.org.hibernate=ERROR
logging.level.com.zaxxer.hikari=ERROR
spring.mvc.pathmatch.matching-strategy=ant_path_matcher

# Remove any existing Thymeleaf configurations if not used
spring.mvc.view.prefix=
spring.mvc.view.suffix=

# Serve React's build files
#spring.web.resources.static-locations=classpath:/static/,file:frontend/build/

# Optional: Handle 404 errors and unknown paths
#spring.mvc.throw-exception-if-no-handler-found=true
spring.mvc.static-path-pattern=/**
spring.web.resources.add-mappings=true
spring.web.resources.static-locations=classpath:/static/

server.port=8080







